version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - foodmate-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: foodmate
      POSTGRES_PASSWORD: foodmate
      POSTGRES_DB: foodmate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodmate-net
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: foodmate
      POSTGRES_PASSWORD: foodmate
      POSTGRES_DB: foodmate
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - foodmate-net

# En esta etapa solo preparamos los contenedores base.
# Después agregaremos cada microservicio aquí.

networks:
  foodmate-net:
    driver: bridge

volumes:
  pgdata:
